version: "3"

services:
  backend:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - "./media:/app/media"
    environment:
      DJANGO_DATABASE_HOST: "mysql"
      DJANGO_DATABASE_NAME: "backend"
      DJANGO_DATABASE_USER: "backend"
      DJANGO_DATABASE_PASSWORD: "backend"
      DJANGO_CONFIG_SECRETKEY: "ihateyou"
    depends_on:
      - "mysql"

  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "backend"
      MYSQL_USER: "backend"
      MYSQL_PASSWORD: "backend"
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
